### ISSUE TITLE
Crash on Android 6.0 

### ISSUE THREAD

**Issue by trihung93** [filestack/filepicker-android#109]
#Crash when open Camera . 

    java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.asus.camera/.CameraApp clip={text/uri-list U:content://media/external/images/media/2534} (has extras) } from ProcessRecord{6f867b7 19454:com.app.app/u0a456} (pid=19454, uid=10456) with revoked permission android.permission.CAMERA
                                                                          at android.os.Parcel.readException(Parcel.java:1620)
                                                                          at android.os.Parcel.readException(Parcel.java:1573)
                                                                          at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2695)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:4001)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3962)
                                                                          at io.filepicker.Filepicker.takePhoto(Filepicker.java:638)
                                                                          at io.filepicker.Filepicker.openCamera(Filepicker.java:621)
                                                                          at io.filepicker.NodesFragment.openDir(NodesFragment.java:231)
                                                                          at io.filepicker.NodesFragment.access$000(NodesFragment.java:29)
                                                                          at io.filepicker.NodesFragment$1.onItemClick(NodesFragment.java:140)
                                                                          at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                          at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                          at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                          at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:756)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)

**Comment by trihung93** [comment]
Its work if have 
```

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```
