### ISSUE TITLE
Filepicker crashes when Gallery->Drive photo selected

### ISSUE THREAD

**Issue by marcoRS** [filestack/filepicker-android#77]
Filepicker always crashes when selecting a photo from Gallery -> Drive . This is happening on a HTC One m7 with Android 5.0.1. 

 Below is the logcat:
java.lang.NullPointerException
       at io.filepicker.services.ContentService.handleActionUploadFile(ContentService.java:158)
       at io.filepicker.services.ContentService.onHandleIntent(ContentService.java:101)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

![gallery-drive](https://cloud.githubusercontent.com/assets/507510/6767955/e0ca82dc-d00c-11e4-93d0-dd4fbaf32ea5.png)

**Comment by janhudzik** [comment]
Fixed in 32806765daa36bb7554a2428aec61e9493a281b0. Will be available in 3.10.0 release.
