### ISSUE TITLE
EventBus Crash

### ISSUE THREAD

**Issue by marcoRS** [filestack/filepicker-android#79]
I'm starting to get reports of a crash associated with an EventBus:

java.lang.NullPointerException
       at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:376)
       at de.greenrobot.event.EventBus.post(EventBus.java:263)
       at io.filepicker.services.ContentService.handleError(ContentService.java:220)
       at io.filepicker.services.ContentService.access$000(ContentService.java:34)
       at io.filepicker.services.ContentService$1.failure(ContentService.java:129)
       at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

I am currently using Filepicker 3.8.11

**Comment by SleeplessByte** [comment]
I've had similar crashes.

**Comment by janhudzik** [comment]
Already resolved.
