### ISSUE TITLE
NoClassDefFoundError occure when pick file from cloud storage srevice

### ISSUE THREAD

**Issue by RajeshMobello** [filestack/filepicker-android#93]
java.lang.NoClassDefFoundError: retrofit.RestAdapter$Builder
 at io.filepicker.api.FpApiClient.getRestAdapter(FpApiClient.java:84)
at io.filepicker.api.FpApiClient.setFpApiClient(FpApiClient.java:68)
at io.filepicker.api.FpApiClient.getFpApiClient(FpApiClient.java:52)
at io.filepicker.services.ContentService.handleActionGetContent(ContentService.java:150)
at io.filepicker.services.ContentService.onHandleIntent(ContentService.java:127)
t android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by RajeshMobello** [comment]
I am also use latest retrofit library for my application. if i remove this from my application file picker working fine. 
Is there any solution to avoid the error?

**Comment by janhudzik** [comment]
Fixed in https://github.com/filestack/filepicker-android/commit/3c4a79e30e0162efc4b9100f16a159be080448a9. Will be available in 3.10.0 release.
